### ISSUE TITLE
Game is rendered in the lower-left 1/4 of the screen on HiDPI systems

### ISSUE THREAD

**Issue by pchote** [IceReaper/KKnD#10]
This happens on "retina" macOS systems by default, and on Linux when the game is launched as `OPENRA_DISPLAY_SCALE=2 ./KKnD-release-20181215b.AppImage`.  This is almost certainly a regression from the window resizing changes, which we have not yet merged upstream.

![](https://i.imgur.com/BHwB8x2.png)

**Comment by IceReaper** [comment]
Closing this issue as the affected feature is removed and will be redone later.
