### ISSUE TITLE
Forum login prompt text overflows its dialog

### ISSUE THREAD

**Issue by pchote** [IceReaper/KKnD#12]
<img src="https://user-images.githubusercontent.com/167819/50047701-b98ab500-011f-11e9-91d8-d88cb1a77171.png">

**Comment by IceReaper** [comment]
Yeah, the default openra ui isnt tinkered to work with any font size. I will completely replace the main menu in the future anyway. Leaving this open till thats done.

**Comment by pchote** [comment]
Likewise for the sysinfo prompt (screenshot in #21).

**Comment by IceReaper** [comment]
Will be fixed by the new main menu ui.
