### ISSUE TITLE
Crash on Ubuntu 18.04

### ISSUE THREAD

**Issue by AOne-T** [IceReaper/KKnD#17]
Using AppImage the game crashes on startup. OpenRA works well.
Attaching files from ~/.openra/Logs/
[debug.log](https://github.com/IceReaper/KKnD/files/2684892/debug.log)
[exception-2018-12-17T072911Z.log](https://github.com/IceReaper/KKnD/files/2684893/exception-2018-12-17T072911Z.log)
[geoip.log](https://github.com/IceReaper/KKnD/files/2684894/geoip.log)

**Comment by matjaeck** [comment]
AppImage works for me on Ubuntu 18.04. Perhaps you installed a wrong package or are missing one.

**Comment by IceReaper** [comment]
Still trying to figure out what happens, cause on my machines it works too (Ubuntu 18.04, Ubuntu Budgie 18.10, Kubuntu 18.10). No problem so far. Maybe the download or one of the dependencies is broken? (libsdl, liblua, libopenal, mono, ... )

**Comment by IceReaper** [comment]
https://github.com/OpenRA/OpenRA/issues/15824#issuecomment-439203912
Does this help you any further?

**Comment by AOne-T** [comment]
Will redownload and try again. But I already have Mono installed and I repeat that OpenRA, OpenCnC, OpenDune work well

**Comment by AOne-T** [comment]
Reinstalled (actually updated) mono and added lualib 5.1
Now it works
