### ISSUE TITLE
The Sprite used in this game

### ISSUE THREAD

**Issue by dudckd502** [IceReaper/KKnD#185]
Hello.

First of all, thank you for creating a good mod. It was nice to have memories of playing back in the day.

I don't have a problem. I want to ask you something.

I also want to try making kknd mode but I didn't know how to open the file in the original game, so I couldn't get the Sprite file of characters, buildings, etc.

I think OpenKrush only partially uses the images of the characters and buildings used, so if possible, can you share them if you have a full Sprite file?

Thank you.

**Comment by IceReaper** [comment]
Hello,

KKnD is currently owned by Ziggurat. I already had to change the name of the project and try to not ship any copyrighted material as i got in contact with them regarding my ~~Remake~~ mod. Thats also why OpenKrush relies on loading the original files as-is and does require a validated legal installation. Its not abandonware at all, and the IP owner realy cares about it. To not get into legal issues, i will not share any of the original game sprites. Also I highly suggest not using them in any other third-party product. Some individual sprites for a wiki or fan-page might be fine, but using those assets could realy get you into some legal trouble. If you have more questions, feel free to join our discord and discuss that with us. Closing this issue for now, as its not an OpenKrush related issue.

Still wish you the best with your modding project!

**Comment by dudckd502** [comment]
Hello.

Thanks for the reply.

I understand the current situation very well. So, I tried to open the
original file of the game using 'UnitExtract' and so on, but I couldn't
find the Sprite file.

I would appreciate it if you could tell me a good way to use it to open the
original game file.

Thank you.

2024년 8월 29일 (목) 오후 10:43, Andre Mohren ***@***.***>님이 작성:

**Comment by IceReaper** [comment]
Those tools use common file formats. However game archives of that time are mostly selfmade. There is no common way to parse them. It requires manual investigation and reverse engineering/ reconstruct a parsing logic. You won't find any software around to open them.

It took me months of work looking at a hex editor and a lot of try&error to figure those formats out
