### ISSUE TITLE
vechicles auto-target

### ISSUE THREAD

**Issue by jamerlan** [IceReaper/KKnD#19]
Thanks for the remake!

But vechicles are not working as expected. They don't auto-targeting enemy units on the move and not shooting them. That makes many of them useless.

In original KKND they were shooting on the move.

**Comment by IceReaper** [comment]
Yeah thats a known issue in openra, i already have it on my todo list, has to be fixed in openra itself.

**Comment by GraionDilach** [comment]
Also see OpenRA/OpenRA#14009.

**Comment by pchote** [comment]
Fixed in https://github.com/OpenRA/OpenRA/pull/16112.
