### ISSUE TITLE
user friendly bunkers

### ISSUE THREAD

**Issue by jamerlan** [IceReaper/KKnD#20]
It's not very clear to players how to activate bunkers.
Or how long to wait for the new robot.
Maybe it's possible to make it a little bit more user friendly?

Personally I was searching some help ingame (like FAQ), then I was searching a website (FAQ and other pages) and still was unable to find instructions how bunkers works. 

In original KKND bunkers were activated just when you are moving a unit near. Looks like in kknd remake you need to bring a special guy for that.

**Comment by matjaeck** [comment]
Can we have a tooltip description for it?

**Comment by IceReaper** [comment]
Bunkers open as in the original game: put an unit next to it, done.
In multiplayer (and skirmish) however they are closed for a particular amount of time (10 minutes on normal speed) + a random time afterwards (1:1000 chance per game tick, which means 25 times per second). This works the same as in KKnD Xtreme skirmish mode.
Only KKnD 2 has a special mechanic, which requires a mechanic to open it.
As opening is random, and the ejected unit is random, a tooltip would not be able to show usefull information.
In KKnD1 the flashing top indicates it can be opened.
In KKnD2 it works the opposite: there is a laser-lock which disappears when its unlocked.

**Comment by jamerlan** [comment]
Many aspects of original game were not user friendly. And you made them user friendly. Like upgrades.
For example: I completed 95% of the missions using only infantry. Because I had no idea how to upgrade buildings. I could not win only last 2 missions for each faction because of the rocket units (1 rocket unit could kill a whole field of my infantry). I had no internet and no manual.. so I was not even thinking that upgrade is possible. I was stuck at the last missions and I was trying over and over.. and then I upgraded my first building by an accident. I was shocked...

Maybe you can add a FAQ: how bunker works, what give you upgrade of "upgrade" building etc.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/issues/3788 could be useful here.

**Comment by IceReaper** [comment]
We will put that on the website, not ingame. closing for now.
