### ISSUE TITLE
Linux launch failure

### ISSUE THREAD

**Issue by Zogg** [IceReaper/KKnD#23]
When launching AppImage:

```bash
./KKnD-release-20181216.AppImage
exception inside UnhandledException handler: Attempted to access a missing member.

[ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method 'Array.Empty' not found.
  at OpenRA.ExceptionHandler.BuildExceptionReport (System.Exception ex) <0x408a5e60 + 0x00043> in <filename unknown>:0 
  at OpenRA.ExceptionHandler.HandleFatalError (System.Exception ex) <0x4089b940 + 0x00433> in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) <0x40873d60 + 0x0010f> in <filename unknown>:0 
```

OS: Ubuntu 16.04.5 LTS 
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)

**Comment by IceReaper** [comment]
Try updating your mono Installation

**Comment by pchote** [comment]
Adding mono to the AppImage is planned upstream, but that is easier said than done because it depends on first removing `System.Drawing` from the entire codebase  because that depends on `libgdiplus` which depends on a large number of other libraries that we don't want to package.

**Comment by IceReaper** [comment]
After the refactoring process is through, i will completely overhaul the readme, telling precisely what is required to get this running. Otherwise bundling mono or .net core should be a feature request to OpenRA itself.
