### ISSUE TITLE
Saboteurs/Vandals cannot target buildings which are behind shroud

### ISSUE THREAD

**Issue by Dzierzan** [IceReaper/KKnD#31]
It appears Saboteurs/Vandals cannot target buildings which are behind shroud. They have to "see" the target in order to be able to enter the neutral/enemy building. If you target the enemy building which you have revealed previously and is behind the shroud, you can attack the structure, but conquering option is not set as default, you have to hold CTRL button to be able to capture it.

**Comment by matjaeck** [comment]
Potentially related: OpenRA/OpenRA#16150

**Comment by IceReaper** [comment]
Has been fixed in the engine. Closing this as this will be automatically fixed for the next rebase.
