### ISSUE TITLE
Excess RAM used in map editor

### ISSUE THREAD

**Issue by C3pa** [IceReaper/KKnD#78]
The program uses almost 2 Gb of RAM when max map size is used (999 hight and 999 width). Maybe nobody will make that large map, but for this kind of game, I believe the map editor uses too much RAM and there may be room for some optimization.

Example screenshot:
![Screenshot](https://user-images.githubusercontent.com/41503714/84909734-51bb7e80-b0b6-11ea-9787-5f18cb4bdce1.png)
The map was just generated and nothing has been actually placed

**Comment by IceReaper** [comment]
so we have 1 million tiles, would make 1mb if every tile was 1 byte. or in other words as the base game also loads up all actors, all available tiles, not only the ones used in this map etc.  and we assume only 1gb being used by the map itself, and every tile has additional data, this amount of ram is amost expected for this map size

**Comment by Dzierzan** [comment]
Well, it's more of ORA issue, although that's a big map we are talking about so... that's kinda expected. Closing.
